/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Osoba;
import domen.Skije;
import domen.Zaposleni;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import mainController.MainController;

/**
 *
 * @author Anđelija
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        txtulogovani = new javax.swing.JLabel();
        txtdatumpreuzimanja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbosoba = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablestavke = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cbskije = new javax.swing.JComboBox<>();
        btnobrisistavku = new javax.swing.JButton();
        btndodajstavku = new javax.swing.JButton();
        btnkreirajiznajmljivanje = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtukupaniznos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtdatumpovratka = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbzaposleni = new javax.swing.JComboBox<>();
        btnizmeniiznajmljivanje = new javax.swing.JButton();
        btnizmenistavku = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemradnasmena = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtulogovani.setText("Ulogovan: ");

        txtdatumpreuzimanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatumpreuzimanjaActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum preuzimanja:  (dd/MM/yyyy)");

        jLabel3.setText("Zaposleni:");

        jLabel4.setText("Osoba:");

        tablestavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablestavke);

        jLabel5.setText("Model i veličina skija:");

        btnobrisistavku.setText("Obriši stavku");
        btnobrisistavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnobrisistavkuActionPerformed(evt);
            }
        });

        btndodajstavku.setText("Dodaj stavku");

        btnkreirajiznajmljivanje.setText("Ubaci iznajmljivanje");

        jLabel6.setText("Ukupan iznos:");

        txtdatumpovratka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatumpovratkaActionPerformed(evt);
            }
        });

        jLabel7.setText("Datum povratka:  (dd/MM/yyyy)");

        jLabel1.setText("ZA STAVKU:");

        btnizmeniiznajmljivanje.setText("Izmeni Iznajmljivanje");

        btnizmenistavku.setText("Izmeni stavku");
        btnizmenistavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnizmenistavkuActionPerformed(evt);
            }
        });

        jMenu3.setText("Osoba");

        jMenuItem3.setText("Prikazi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setText("Ubaci");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Iznajmljivanje");

        jMenuItem6.setText("Prikazi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Radna smena");

        itemradnasmena.setText("Prikazi");
        itemradnasmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemradnasmenaActionPerformed(evt);
            }
        });
        jMenu1.add(itemradnasmena);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnobrisistavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndodajstavku, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(btnizmenistavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbosoba, 0, 343, Short.MAX_VALUE)
                                    .addComponent(cbzaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdatumpovratka, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtdatumpreuzimanja, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbskije, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtukupaniznos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnizmeniiznajmljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkreirajiznajmljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtulogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtulogovani))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdatumpreuzimanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cbzaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdatumpovratka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(cbosoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbskije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndodajstavku, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnobrisistavku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnizmenistavku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtukupaniznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnkreirajiznajmljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnizmeniiznajmljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdatumpreuzimanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatumpreuzimanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatumpreuzimanjaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MainController.getInstance().prikaziOsobaPrikaziF();      
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
          MainController.getInstance().prikaziUbaciOsobuF();      
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void txtdatumpovratkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatumpovratkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatumpovratkaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         MainController.getInstance().prikaziIznajmljivanjaF();  
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void itemradnasmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemradnasmenaActionPerformed
            MainController.getInstance().prikaziUbaciRadnuSmenuF();  
    }//GEN-LAST:event_itemradnasmenaActionPerformed

    private void btnizmenistavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnizmenistavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnizmenistavkuActionPerformed

    private void btnobrisistavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnobrisistavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnobrisistavkuActionPerformed

    public JLabel getTxtulogovani() {
        return txtulogovani;
    }

    public void setTxtulogovani(JLabel txtulogovani) {
        this.txtulogovani = txtulogovani;
    }

//   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndodajstavku;
    private javax.swing.JButton btnizmeniiznajmljivanje;
    private javax.swing.JButton btnizmenistavku;
    private javax.swing.JButton btnkreirajiznajmljivanje;
    private javax.swing.JButton btnobrisistavku;
    private javax.swing.JComboBox<Osoba> cbosoba;
    private javax.swing.JComboBox<Skije> cbskije;
    private javax.swing.JComboBox<Zaposleni> cbzaposleni;
    private javax.swing.JMenuItem itemradnasmena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablestavke;
    private javax.swing.JTextField txtdatumpovratka;
    private javax.swing.JTextField txtdatumpreuzimanja;
    private javax.swing.JTextField txtukupaniznos;
    private javax.swing.JLabel txtulogovani;
    // End of variables declaration//GEN-END:variables

    public JButton getBtndodajstavku() {
        return btndodajstavku;
    }

    public void setBtndodajstavku(JButton btndodajstavku) {
        this.btndodajstavku = btndodajstavku;
    }

    public JButton getBtnkreirajiznajmljivanje() {
        return btnkreirajiznajmljivanje;
    }

    public void setBtnkreirajiznajmljivanje(JButton btnkreirajiznajmljivanje) {
        this.btnkreirajiznajmljivanje = btnkreirajiznajmljivanje;
    }

    public JButton getBtnobrisistavku() {
        return btnobrisistavku;
    }

    public void setBtnobrisistavku(JButton btnobrisistavku) {
        this.btnobrisistavku = btnobrisistavku;
    }

    public JComboBox<Osoba> getCbosoba() {
        return cbosoba;
    }

    public void setCbosoba(JComboBox<Osoba> cbosoba) {
        this.cbosoba = cbosoba;
    }

    public JComboBox<Skije> getCbskije() {
        return cbskije;
    }

    public void setCbskije(JComboBox<Skije> cbskije) {
        this.cbskije = cbskije;
    }

    public JTable getTablestavke() {
        return tablestavke;
    }

    public void setTablestavke(JTable tablestavke) {
        this.tablestavke = tablestavke;
    }

    public JTextField getTxtdatumpovratka() {
        return txtdatumpovratka;
    }

    public void setTxtdatumpovratka(JTextField txtdatumpovratka) {
        this.txtdatumpovratka = txtdatumpovratka;
    }

    public JTextField getTxtdatumpreuzimanja() {
        return txtdatumpreuzimanja;
    }

    public void setTxtdatumpreuzimanja(JTextField txtdatumpreuzimanja) {
        this.txtdatumpreuzimanja = txtdatumpreuzimanja;
    }

    public JTextField getTxtukupaniznos() {
        return txtukupaniznos;
    }

    public void setTxtukupaniznos(JTextField txtukupaniznos) {
        this.txtukupaniznos = txtukupaniznos;
    }

    public JComboBox<Zaposleni> getCbzaposleni() {
        return cbzaposleni;
    }

    public void setCbzaposleni(JComboBox<Zaposleni> cbzaposleni) {
        this.cbzaposleni = cbzaposleni;
    }

    public JButton getBtnizmeniiznajmljivanje() {
        return btnizmeniiznajmljivanje;
    }

    public void setBtnizmeniiznajmljivanje(JButton btnizmeniiznajmljivanje) {
        this.btnizmeniiznajmljivanje = btnizmeniiznajmljivanje;
    }

    public JButton getBtnizmenistavku() {
        return btnizmenistavku;
    }

    public void setBtnizmenistavku(JButton btnizmenistavku) {
        this.btnizmenistavku = btnizmenistavku;
    }

    public void dodajStavkuAddActionListener(ActionListener actionListener) {
        btndodajstavku.addActionListener(actionListener);
    }
    
      public void obrisiStavkuAddActionListener(ActionListener actionListener) {
        btnobrisistavku.addActionListener(actionListener);
    }

    public void dodajIznajmljivanjeAddActionListener(ActionListener actionListener) {
        btnkreirajiznajmljivanje.addActionListener(actionListener);
    }

    public void promeniIznajmljivanjeAddActionListener(ActionListener actionListener) {
        btnizmeniiznajmljivanje.addActionListener(actionListener);
    }

    public void promeniStavkuAddActionListener(ActionListener actionListener) {
        btnizmenistavku.addActionListener(actionListener);
    }
   
}
