/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Clanstvo;
import java.awt.event.ActionListener;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Anđelija
 */
public class PrikaziOsobuForma extends javax.swing.JFrame {

    /**
     * Creates new form OsobaPretraziForma
     */
    public PrikaziOsobuForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableosobe = new javax.swing.JTable();
        btnobrisi = new javax.swing.JButton();
        btnpromeni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtime = new javax.swing.JTextField();
        txtprezime = new javax.swing.JTextField();
        txttelefon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtjmbg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbclanstvo = new javax.swing.JComboBox<>();
        btnpretrazi = new javax.swing.JButton();
        btnponistifilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableosobe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableosobe);

        btnobrisi.setText("Obriši");

        btnpromeni.setText("Promeni");
        btnpromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpromeniActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Telefon");

        txtprezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprezimeActionPerformed(evt);
            }
        });

        jLabel4.setText("JMBG");

        txtjmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmbgActionPerformed(evt);
            }
        });

        jLabel5.setText("Clanstvo");

        btnpretrazi.setText("Pretrazi");

        btnponistifilter.setText("Ponisti filtere");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnobrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnpromeni, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtime, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtprezime)
                            .addComponent(txttelefon))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnpretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnponistifilter, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbclanstvo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtprezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbclanstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnponistifilter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnobrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpromeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpromeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpromeniActionPerformed

    private void txtprezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprezimeActionPerformed

    private void txtjmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmbgActionPerformed

    /**
     * @param args the command line arguments
     */
  

    public JTable getTableosobe() {
        return tableosobe;
    }

    public JButton getBtnobrisi() {
        return btnobrisi;
    }

    public JButton getBtnponistifilter() {
        return btnponistifilter;
    }

    public void setBtnponistifilter(JButton btnponistifilter) {
        this.btnponistifilter = btnponistifilter;
    }

    public JButton getBtnpretrazi() {
        return btnpretrazi;
    }

    public void setBtnpretrazi(JButton btnpretrazi) {
        this.btnpretrazi = btnpretrazi;
    }

    public JButton getBtnpromeni() {
        return btnpromeni;
    }

    public void setBtnpromeni(JButton btnpromeni) {
        this.btnpromeni = btnpromeni;
    }

    public JComboBox<Clanstvo> getCbclanstvo() {
        return cbclanstvo;
    }

    public void setCbclanstvo(JComboBox<Clanstvo> cbclanstvo) {
        this.cbclanstvo = cbclanstvo;
    }

 
    public JTextField getTxtime() {
        return txtime;
    }

    public void setTxtime(JTextField txtime) {
        this.txtime = txtime;
    }

    public JTextField getTxtjmbg() {
        return txtjmbg;
    }

    public void setTxtjmbg(JTextField txtjmbg) {
        this.txtjmbg = txtjmbg;
    }

    public JTextField getTxtprezime() {
        return txtprezime;
    }

    public void setTxtprezime(JTextField txtprezime) {
        this.txtprezime = txtprezime;
    }

    public JTextField getTxttelefon() {
        return txttelefon;
    }

    public void setTxttelefon(JTextField txttelefon) {
        this.txttelefon = txttelefon;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnobrisi;
    private javax.swing.JButton btnponistifilter;
    private javax.swing.JButton btnpretrazi;
    private javax.swing.JButton btnpromeni;
    private javax.swing.JComboBox<Clanstvo> cbclanstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableosobe;
    private javax.swing.JTextField txtime;
    private javax.swing.JTextField txtjmbg;
    private javax.swing.JTextField txtprezime;
    private javax.swing.JTextField txttelefon;
    // End of variables declaration//GEN-END:variables

    public void obrisiAddActionListener(ActionListener actionListener) {
        btnobrisi.addActionListener(actionListener);
    }
    
    
    public void promeniAddActionListener(ActionListener actionListener) {
        btnpromeni.addActionListener(actionListener);
    }
    
    public void pretraziAddActionListener(ActionListener actionListener) {
        btnpretrazi.addActionListener(actionListener);
    }

    public void ponistiFilterAddActionListener(ActionListener actionListener) {
        btnponistifilter.addActionListener(actionListener);
    }
     
     
}
